### ISSUE TITLE
Doesnt work in Windows 10

### ISSUE THREAD

**Issue by Egorvoz** [tststs/atom-ternjs#235] opened 2016-05-23 19:32 UTC
Download and install atom tern-js.
All autocomplete in atom doest work. Delete this pakcage and all good.
In ublime all work good

**Comment by vazh** [comment] 2016-05-26 10:07
yeah, same problem with a lot of us.
#230 discussing the same thing

**Comment by tststs** [comment] 2016-06-16 19:40
duplicate of #230

**Closed by tststs** 2016-06-16 19:40 UTC
