### ISSUE TITLE
Tern server crash on specific number format

### ISSUE THREAD

**Issue by bendem** [tststs/atom-ternjs#66] opened 2015-05-05 09:51 UTC
When typing a number using the `0x...` format, the Tern server crashes with this error:
```
atom-ternjs
~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/acorn_loose.js:1260 throw e; ^ SyntaxError: Expected number in radix 16 (23:6)
at Parser.pp.raise (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/acorn.js:1009:13) at Parser.pp.readRadixNumber (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/acorn.js:2779:25)
at Parser.pp.getTokenFromCode (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/acorn.js:2628:52)
at Parser.pp.readToken (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/acorn.js:2385:15)
at Parser.pp.nextToken (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/acorn.js:2377:71)
at Parser.pp.next (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/acorn.js:2326:8)
at LooseParser.lp.readToken (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/acorn_loose.js:1217:17)
at LooseParser.lp.next (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/acorn_loose.js:1203:77)
at LooseParser.lp.eat (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/acorn_loose.js:653:10)
at LooseParser.lp.parseObj (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/acorn_loose.js:449:10)
```

**Comment by tststs** [comment] 2015-05-10 19:31
Couldn't reproduce it.

You may try to reinstall the package to get the latest version of tern.
If this doesn't solve the problem, please post an issue to <a href="https://github.com/marijnh/tern">marijnh/tern</a> with a code-snippet, so the issue can be reproduced.

thx
tststs

**Comment by tststs** [comment] 2015-05-10 19:39
Yep, server crashes. You may post an issue to <a href="https://github.com/marijnh/tern">marijnh/tern</a>

**Comment by tststs** [comment] 2015-05-15 16:21
should be fixed after update. thx @marijnh

**Closed by tststs** 2015-05-15 16:21 UTC
