### ISSUE TITLE
This plugin actually disabled the autocomplete function in the file that is not in the root path.

### ISSUE THREAD

**Issue by huiboliu** [tststs/atom-ternjs#233] opened 2016-05-20 07:17 UTC
This plugin actually disabled the autocomplete feature in the file that is not in the root path.
When i disable this plugin, the autocomplete feature can then work fine. This is wired and unconvinient.

**Comment by Andrey-Zhiryakov** [comment] 2016-05-22 18:12
I have this trouble to on winodws 10 with lastest atom version.

**Comment by belchevgb** [comment] 2016-05-26 14:59
I have the same problem using Windows 10 and Atom latest version. Hope to fix it soon!

**Comment by shachar-i** [comment] 2016-05-29 21:49
Got this issue as well

**Comment by WangQianliang** [comment] 2016-06-10 15:56
same issue

**Comment by tststs** [comment] 2016-06-16 19:49
duplicate of #230

**Closed by tststs** 2016-06-16 19:49 UTC
