### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'atom://config'

### ISSUE THREAD

**Issue by LittleWebCoder** [tststs/atom-ternjs#148] opened 2015-10-16 05:45 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.8.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'atom://config'

```
At fs.js:854

Error: ENOENT: no such file or directory, stat 'atom://config'
    at Error (native)
    at fs.statSync (fs.js:854:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
    at Helper.module.exports.Helper.isDirectory (/Users/work/.atom/packages/atom-ternjs/lib/atom-ternjs-helper.coffee:25:8)
    at Manager.module.exports.Manager.checkPaths (/Users/work/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:122:36)
    at /Users/work/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:38:8
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:279:29)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:41:32)
    at emitTwo (events.js:87:13)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "atom-ternjs": {}
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.8.3
autocomplete-bibtex, v0.6.1
autocomplete-paths, v1.0.2
color-picker, v2.0.13
docblockr, v0.7.3
emmet, v2.3.13
file-icons, v1.6.10
minimap, v4.13.4

# Dev
No dev packages
```

**Comment by jordanbtucker** [comment] 2015-10-16 05:46
Duplicate of #147

**Closed** 2015-10-16 05:48 UTC

**Comment by jordanbtucker** [comment] 2015-10-16 05:56
Even though it's a different error message, both issues have the same source.
