### ISSUE TITLE
Deprecated selector in `atom-ternjs\styles\atom-ternjs.less`

### ISSUE THREAD

**Issue by Inancor** [tststs/atom-ternjs#284] opened 2017-01-10 22:18 UTC
In `atom-ternjs\styles\atom-ternjs.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .scroll-view .source.js .function:not(.meta):not(.type).atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .function:not(.meta):not(.type).atom-ternjs-hover,
atom-text-editor::shadow .scroll-view .source.js .class.name.atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .class.name.atom-ternjs-hover,
atom-text-editor::shadow .scroll-view .source.js .support.atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .support.atom-ternjs-hover,
atom-text-editor::shadow .scroll-view .source.js .constant.other.atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .constant.other.atom-ternjs-hover,
atom-text-editor::shadow .scroll-view .source.js .object:not(.delimiter).atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .object:not(.delimiter).atom-ternjs-hover,
atom-text-editor::shadow .scroll-view .source.js .variable.atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .variable.atom-ternjs-hover` => `atom-text-editor.editor .scroll-view .syntax--source.syntax--js .syntax--function:not(.meta):not(.type).atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .function:not(.meta):not(.type).atom-ternjs-hover,
atom-text-editor.editor .scroll-view .syntax--source.syntax--js .syntax--class.syntax--name.atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .class.name.atom-ternjs-hover,
atom-text-editor.editor .scroll-view .syntax--source.syntax--js .syntax--support.atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .support.atom-ternjs-hover,
atom-text-editor.editor .scroll-view .syntax--source.syntax--js .syntax--constant.syntax--other.atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .constant.other.atom-ternjs-hover,
atom-text-editor.editor .scroll-view .syntax--source.syntax--js .syntax--object:not(.delimiter).atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .object:not(.delimiter).atom-ternjs-hover,
atom-text-editor.editor .scroll-view .syntax--source.syntax--js .syntax--variable.atom-ternjs-hover,
atom-text-editor .scroll-view .source.js .variable.atom-ternjs-hover`

* `atom-text-editor[data-grammar="source js"] .atom-ternjs-definition-marker div,
atom-text-editor[data-grammar="source js"]::shadow .atom-ternjs-definition-marker div` => `atom-text-editor[data-grammar="source js"] .atom-ternjs-definition-marker div,
atom-text-editor[data-grammar="source js"].editor .atom-ternjs-definition-marker div`

* `atom-text-editor[data-grammar="source js"] .atom-ternjs-definition-marker.active div,
atom-text-editor[data-grammar="source js"]::shadow .atom-ternjs-definition-marker.active div` => `atom-text-editor[data-grammar="source js"] .atom-ternjs-definition-marker.active div,
atom-text-editor[data-grammar="source js"].editor .atom-ternjs-definition-marker.active div`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Inancor** [comment] 2017-01-10 22:18
Uncertain if this is a duplicate. Please tag if necessary.

**Comment by hasansan07** [comment] 2017-01-11 21:28
It seems that this is a duplicate of #265

**Comment by Inancor** [comment] 2017-01-11 22:17
It seems to be returning the same message, though on different element selectors. `atom-text-editor::shadow` vs `atom-text-editor`, for example.

**Comment by Nalyvaiko** [comment] 2017-01-15 12:23
Is it fixed??? I still have 3 deprecations.

**Closed** 2017-01-21 14:14 UTC
