### ISSUE TITLE
Doesn't autocomplete JavaScript in HTML files?

### ISSUE THREAD

**Issue by ipkpjersi** [tststs/atom-ternjs#338] opened 2018-01-21 18:25 UTC
Hi,

I am using the latest Atom on Ubuntu 16.04 and I am unable to get JavaScript to autocomplete in HTML files.

Here is a screenshot of autocomplete not working: ![](https://i.imgur.com/T5HYnSp.png)

Here is my config file: ![](https://i.imgur.com/D1nlytr.png)

**Comment by tststs** [comment] 2019-03-03 16:09
completion in html files is currently not supported.

**Comment by tststs** [comment] 2019-03-03 20:28
duplicate of #317

**Closed by tststs** 2019-03-03 20:28 UTC
Labels: enhancement
