### ISSUE TITLE
Cannot find tern even if PATH is properly set

### ISSUE THREAD

**Issue by renkun-ken** [tststs/atom-ternjs#91] opened 2015-06-10 12:33 UTC
I set my user-PATH and global-PATH to include the location containing `tern` and tested it in `cmd` but when I open a `css` file, atom still cannot find `tern` and show the following error message:

```
Failed to spawn command C:\Users\Kun\.atom\packages\atom-ternjs\node_modules\.bin\tern. Make sure C:\Users\Kun\.atom\packages\atom-ternjs\node_modules\.bin\tern is installed and on your PATH
```

I input `tern` in `cmd` and it runs without error.

My system is Windows 8.1 x64 and Atom 0.207.

**Comment by itsnotvalid** [comment] 2015-06-11 03:16
@renkun-ken same problem here as in #90. However tern actually do start after this error.

**Comment by tststs** [comment] 2015-06-18 12:19
I don't know exactly what happens, but i think it's related to <a href="https://github.com/atom/atom/issues/2887">https://github.com/atom/atom/issues/2887</a>

The error is thrown, but atom-ternjs still works right?

**Comment by tststs** [comment] 2015-06-29 13:59
duplicate of #90

**Closed by tststs** 2015-06-29 13:59 UTC
