### ISSUE TITLE
Uncaught TypeError: Cannot set property 'isDirty' of undefined

### ISSUE THREAD

**Issue by amodmulay** [tststs/atom-ternjs#315] opened 2017-05-02 14:14 UTC
[Enter steps to reproduce:]

1. Ctrl-Z
2. Backspace

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package 0.18.2

### Stack Trace

Uncaught TypeError: Cannot set property 'isDirty' of undefined

```
At C:\Users\amodm1\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:833

TypeError: Cannot set property 'isDirty' of undefined
    at /packages/atom-ternjs/lib/atom-ternjs-manager.js:262:23
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/app.asar/node_modules/text-buffer/lib/text-buffer.js:680:20)
    at TextBuffer.module.exports.TextBuffer.applyChange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:664:12)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/app.asar/node_modules/text-buffer/lib/text-buffer.js:877:16)
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:831:14)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1594:26)
    at /app.asar/src/text-editor.js:1155:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/app.asar/src/text-editor.js:2568:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:2534:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1153:19)
    at TextEditor.module.exports.TextEditor.backspace (/app.asar/src/text-editor.js:1144:19)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at /app.asar/src/register-default-commands.js:425:21)
    at /app.asar/src/register-default-commands.js:666:34
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1594:26)
    at /app.asar/src/register-default-commands.js:665:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -7:47.8.0 core:save (input.hidden-input)
     -7:33.7.0 core:backspace (input.hidden-input)
     -7:30.3.0 core:delete (input.hidden-input)
     -7:29.7.0 core:backspace (input.hidden-input)
  2x -7:28.5.0 core:save (input.hidden-input)
     -1:17.6.0 core:backspace (input.hidden-input)
     -1:17 core:move-right (input.hidden-input)
     -1:16.7.0 core:backspace (input.hidden-input)
     -1:16.1.0 core:move-right (input.hidden-input)
     -1:15.6.0 core:backspace (input.hidden-input)
  3x -1:14.1.0 core:save (input.hidden-input)
  2x -0:42.1.0 core:backspace (input.hidden-input)
 11x -0:34.1.0 core:undo (input.hidden-input)
     -0:18.9.0 core:backspace (input.hidden-input)
     -0:15 core:delete (input.hidden-input)
  2x -0:09.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-clock 0.1.7 
atom-ternjs 0.18.2 
autocomplete-json 5.4.0 
linter-write-good 0.9.0 
node-debugger 1.10.1 
```

**Comment by ismyrnow** [comment] 2017-05-02 15:55
I found myself in a situation where I couldn't even edit the JS file I was working in. Any keystroke would trigger this error.

Closing and re-opening the file did resolve the issue.

**Comment by amodmulay** [comment] 2017-05-02 18:47
same here. restarting fixes it

**Comment by Shiggiddie** [comment] 2017-05-02 18:48
I had a similar issue, following the configuration steps in the package's README fixed the problem for me:
```
Configure your project

Open any JavaScript file from within your project
Navigate to Packages -> Atom Ternjs -> Configure project
The config view appears.
Hit "Save & Restart Server" to create/update the .tern-project file
```
From: https://atom.io/packages/atom-ternjs

**Comment by tststs** [comment] 2017-05-03 19:11
duplicate of #295

**Closed by tststs** 2017-05-03 19:11 UTC
