### ISSUE TITLE
The ternjs seem conflict with autocomplete-plus

### ISSUE THREAD

**Issue by Mascot1** [tststs/atom-ternjs#232] opened 2016-05-20 03:25 UTC
When I down load ternjs and I write the js code,it doesn't give me any suggestion. But when uninstall ternjs the autocompelte-plus give me the suggestions .

**Comment by huiboliu** [comment] 2016-05-20 07:18
I get this experience too!

**Comment by vazh** [comment] 2016-05-23 07:08
check #230

**Comment by tststs** [comment] 2016-06-16 19:49
duplicate of #230

**Closed by tststs** 2016-06-16 19:49 UTC
