### ISSUE TITLE
Ternjs sometimes would occupied 100% CPU

### ISSUE THREAD

**Issue by lygstate** [tststs/atom-ternjs#197] opened 2016-01-13 07:41 UTC
And causing the atom editor to be dead.

**Comment by rcrichton** [comment] 2016-01-15 07:11
Perhaps this is the same issue that I'm experiencing here: https://github.com/tststs/atom-ternjs/issues/193

**Comment by tststs** [comment] 2016-01-19 00:15
Duplicate of #193

**Closed by tststs** 2016-01-19 00:15 UTC
