### ISSUE TITLE
Error on startup in win64

### ISSUE THREAD

**Issue by itsnotvalid** [tststs/atom-ternjs#90] opened 2015-06-10 10:35 UTC
I've got errors regarding spawning tern server on windows x64 (win 8.1 x64 in exact).
```
BufferedProcessError: Failed to spawn command `C:\Users\itsnotvalid\.atom\packages\atom-ternjs\node_modules\.bin\tern`. Make sure `C:\Users\itsnotvalid\.atom\packages\atom-ternjs\node_modules\.bin\tern` is installed and on your PATH
```
Note that the tern servers are actually started.

**Comment by tststs** [comment] 2015-07-09 17:13
cc @atom

**Comment by enzy** [comment] 2015-07-27 07:41
I have the same problem, also Win 8.1 x64 here.

**Comment by tststs** [comment] 2015-07-29 16:59
Just tested this with atom 1.0.3 and atom-ternjs 0.7.1.
The error occurs after installing the package but won't reappear again if all instances of atom are closes and atom is reopened. Tested it on Win 8.1 x64.

Does the error still shows up on every startup of atom?

**Comment by enzy** [comment] 2015-07-29 17:13
Every startup on 1.0.2

**Comment by tststs** [comment] 2015-07-29 17:15
yep. please upgrade to 1.0.3. If the problem still occurs, please reinstall atom-ternjs while on 1.0.3.

**Comment by ssebastianj** [comment] 2015-07-30 02:17
I can confirm this issue on a `Windows 7 x86 SP1` + `Atom 1.0.3 (fresh installation)`. With `Atom 1.0.2` the package worked flawlessly.
Already tried reinstalling the package (even deleting the pkg installation folder, just to be sure) with no luck.

**Comment by errantmind** [comment] 2015-08-03 21:58
Same issue on Windows 7 x64, Atom 1.0.3.

I have verified tern is accessible from the command line but the error message says otherwise

**Comment by IamAdamJowett** [comment] 2015-08-10 21:53
Same issue here also, `Windows 10` on `Atom 1.0.5`. Gives me the following error:

    C:\Users\Adam\AppData\Local\atom\app-1.0.5\resources\app.asar\src\buffered-process.js:260
    Uncaught BufferedProcessError: Failed to spawn command `C:\Users\Adam\.atom\packages\atomternjs\node_modules\.bin\tern`. 
    Make sure `C:\Users\Adam\.atom\packages\atom-ternjs\node_modules\.bin\tern` is installed and on your PATH

Just to confirm tern is installed globally, and the above path is in my PATH. Been fine up to today so not sure what changed.

Have also uninstalled and re-installed the package, with the same issue.

**Comment by harryxu** [comment] 2015-08-11 03:33
I have the same issue on Windows 10 with atom 1.0.4.

**Comment by wiggisser** [comment] 2015-08-22 09:04
I have the same issue, Windows 8.1, atom 1.0.7, but only for specific file type. So far, I only noticed this with coffeescript files. Do I need some additional package to make this work for coffeescript?

**Comment by vinzbe** [comment] 2015-09-09 23:25
Same issue with Windows 10, atom 1.0.11.

For some unknown reason, there is no error if I open files located on 2 specific folders. If I rename these folders or try the same content elsewhere I will get the error.

I made sure no instance of atom.exe when testing.

**Comment by zmLGBBM** [comment] 2015-10-14 10:38
@tststs  This (-> https://github.com/edubkendo/atom-elm/pull/20) seems to be a fix for this kinda `spawn error`.

**Comment by isochronous** [comment] 2015-10-14 16:37
Man, it would be amazing if this four month old, highly inconvenient bug were to get a little more attention - or at least some updates so we know it's being worked on.  Right now it feels like Windows users are second-class citizens as the windows issues seem to have the fewest responses from the devs.

**Comment by isochronous** [comment] 2015-10-14 16:56
I can, however, confirm what vinzbe discovered - if you right click on a *folder* and choose "Open with Atom", it seems to work perfectly.  Choosing "Open with Atom" on a file within that folder also works fine, once the folder itself has been opened with atom.  Using the file menu within atom to open a file in any other directory also seems to work, as long as you launched atom by choosing "open with atom" from a folder's context menu.

Basically, the 3 ways it works properly are:

1. Use the "Open in Atom" context menu command on any folder.  From that point on, you can open any file in any folder and have it work, as long as you open them through Atom, rather than through any other app.  
2. Using the "Open in Atom" context menu command on any file in a folder that's previously been opened by the "Open in Atom" context menu entry.
3. Launching atom directly, as long as the files/folders that were open at the time you closed it had been opened through the folder's "open in atom" context menu entry.

I don't know why opening a *folder* using the context menu in explorer seems to be the magic bullet that fixes everything, but it should be an excellent clue to help in fixing the issue.

**Comment by jordanbtucker** [comment] 2015-10-14 18:40
I think it has to do with the fact that there's no project folder when you "Open with Atom" a file in a folder you've never opened in Atom (or a folder you haven't open recently).

**Comment by vinzbe** [comment] 2015-10-14 22:16
It has something to do with the files stored in %userprofile%\.atom\storage

**Comment by jordanbtucker** [comment] 2015-10-15 00:05
Sorry about all the references. I didn't realize it would do this when I amended my commits.

**Closed** 2015-10-15 12:01 UTC
